### ISSUE TITLE
🛠️  fix github action tests

### ISSUE THREAD

**Issue by tyler36** [tyler36/ddev-cypress#2]
Automated tests are currently failing; 

### Github Actions
https://github.com/tyler36/ddev-cypress/actions

### local

- Unable to get tests running locally on WSL
- tests silently fail when trying to load bats support libraries

```shell
❯ bats ./tests 
   install from release                                                                                                                                           2/2
   bats warning: Executed 0 instead of expected 2 tests

2 tests, 0 failures, 2 not run
```

- WSL doesn't properly install support libraries

```shell
$ brew install bats-support bats-assert bats-file
...
==> Installing bats-support from bats-core/bats-core
Error: The following formula cannot be installed from bottle and must be
built from source.
  bats-support
Install Clang or run `brew install gcc`.

$ brew install gcc
...
Warning: gcc 11.2.0_3 is already installed and up-to-date.
To reinstall 11.2.0_3, run:
  brew reinstall gcc
```

## Goal
Tests should
- [ ] assert required files are downloaded
- [ ] assert basic output of command

**Comment by rfay** [comment]
Try installing bats with the make install technique.

**Comment by tyler36** [comment]
Got Bats support tools installed in WSL with after running the following:

```shell
sudo apt-get update
sudo apt-get install build-essential
```
