### ISSUE TITLE
Unable to install on m1 mac

### ISSUE THREAD

**Issue by louis-cuny** [tyler36/ddev-cypress#22]
I tried to install this ddev plugin but I got an error saying that it does not work on arm64. README.md file is saying the opposite

`ddev get tyler36/ddev-cypress --verbose
Downloading https://api.github.com/repos/tyler36/ddev-cypress/tarball/1.0.0 
1.0.0_2409965684.tar.gz 8.73 KiB / ? [-------------------------------------------------------=---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]  89.44% 0s 

Executing pre-install actions: 
+ set -eu -o pipefail
++ arch
++ arch
+ '[' arm64 = arm64 -o arm64 = aarch64 ']'
+ echo 'This package does not work on arm64 machines'
This package does not work on arm64 machines
+ exit 1
 
👎  
could not process pre-install action (0) ''; error=Unable to run action set -x; set -eu -o pipefail
#ddev-nodisplay
if [ "$(arch)" = "arm64" -o "$(arch)" = "aarch64" ]; then 
  echo "This package does not work on arm64 machines"; 
  exit 1; 
fi
: exit status 1, output=+ set -eu -o pipefail
++ arch
++ arch
+ '[' arm64 = arm64 -o arm64 = aarch64 ']'
+ echo 'This package does not work on arm64 machines'
This package does not work on arm64 machines
+ exit 1

 action=#ddev-nodisplay
if [ "$(arch)" = "arm64" -o "$(arch)" = "aarch64" ]; then 
  echo "This package does not work on arm64 machines"; 
  exit 1; 
fi
`

**Comment by tyler36** [comment]
Thank you for openning the issue. 

I don't have access to a macOS so I can't do any testing on it. Recently, there was #21 which I was hoping to get some feedback for a new release.

I've got a copy of PRs open that I hope to merge and release over the next few hours.

**Comment by tyler36** [comment]
OK. Just release `1.1.0` which has some fixes, specifically 413d5c52308e78d8fd144a1cf14d84d72f77b741 which removes the "arm64" check.

Closing.
