### ISSUE TITLE
"Cypress verification timed out." error on mac M2 

### ISSUE THREAD

**Issue by louis-cuny** [tyler36/ddev-cypress#27]
Thank you for your reactivity on last issue.
I could install cypress with last project tag.

But when I run `ddev cypress-open`, I got following error:

Cypress verification timed out.

This command failed with the following output:

/root/.cache/Cypress/12.6.0/Cypress/Cypress --no-sandbox --smoke-test --ping=567

Command timed out after 30000 milliseconds: /root/.cache/Cypress/12.6.0/Cypress/Cypress --no-sandbox --smoke-test --ping=567
Timed out

Platform: linux-arm64 (Debian - 11.6)
Cypress Version: 12.6.0
Failed to run cypress-open -C tests: exit status 1

**Comment by louis-cuny** [comment]
`ddev status` should show more informations ? 
![image](https://github.com/tyler36/ddev-cypress/assets/13121784/941914a1-505c-4edb-a64b-b6cba173e7b7)

**Comment by tyler36** [comment]
Cypress shows exactly the same thing for me.

![ddev-cypress](https://github.com/tyler36/ddev-cypress/assets/7234392/5df14f6e-836e-4664-9357-2243883a8fb2)

**Comment by tyler36** [comment]
You could try changing some of the configuration settings, or cleaering the cache.

https://docs.cypress.io/api/cypress-api/config#Syntax

**Comment by louis-cuny** [comment]
Thanks, I found out cypress browsers are not ready for arm64 processors 
https://github.com/cypress-io/cypress-docker-images/issues/695

I can avoid the problem using rosetta
