### ISSUE TITLE
Add 8 basis test setup from ncatestify

### ISSUE THREAD

**Issue by rogoit** [tyler36/ddev-cypress#39]
Hi, 

thx a lot. Works perfect.

Add plugin as npm dependency
https://github.com/ncatestify/cypress-base-plugin

Add ncatt-base-tests
https://github.com/ncatestify/cypressio-base/tree/main/template/cypress/e2e/ncatt-base-tests

Tests and project will have new features and improvements over the plugin commands.

Feel free to get in touch with me. You also can explain everything with me in a live screenshare session on YouTube.

Keep green
Roland

**Comment by tyler36** [comment]
Closing.

Not sure what "issue" you are presenting. Or how the comments relate to this repo.🤷
