### ISSUE TITLE
What's the project status? and is there a working example?

### ISSUE THREAD

**Issue by TravisCarden** [tyler36/ddev-cypress#41]
👋 Hi! I'm looking to add Cypress testing to my DDEV project, and I haven't been able to get this add-on (specifically the `cypress-open` command) to work, either in my project or in a "hello world" minimal setup. It doesn't look like this project has been updated in a while. What's the current status? Is there a verified "hello world"-style, working example implementation I could try so I can determine whether I'm doing something wrong or there's an upstream issue? Thanks!

**Comment by tyler36** [comment]
Hi @TravisCarden 

The project is currently in a "maintained and working" state. 

There are nightly tests BATS tests that confirm 

- the extensions can be installed
- a simple website served by DDEV can be accessed and contains the expected string.

See `tests/test.bats` for example setups.

**Comment by tyler36** [comment]
>  I haven't been able to get this add-on (specifically the cypress-open command) to work

It's hard to know what's going on. I just tested on WSL with DDEV `1.23.3-33-g88ae3c3a4` and it "works for me". 
If you use a Mac, you might want to look at #38 which is trying to improve the setup guide. Perhaps you have further suggestions there?

**Comment by TravisCarden** [comment]
Thanks for pointing that out, @tyler36. It did surface a couple of things that I was missing--most importantly, the `docker-compose.cypress_extra.yaml` bit. I don't have any further suggestions, but I can affirm that the current proposal is a definite improvement and the additions worked for me.

**Comment by tyler36** [comment]
>  I can affirm that the current proposal is a definite improvement and the additions worked for me.

Thank you for the feedback on #38 .
