### ISSUE TITLE
Can't install plugins inside cypress container

### ISSUE THREAD

**Issue by bserem** [tyler36/ddev-cypress#48]
Coming from Behat I am evaluating Cypress and loving it so far, however I have a legacy of tests written in Cucumber (and I find it easier to write) so I am experimenting with official plugins that allow Cucumber syntax in Cypress.

When I try to install custom cypress plugins via NPM I am getting this error:
```
npm error Your cache folder contains root-owned files, due to a bug in
npm error previous versions of npm which has since been addressed.
npm error
npm error To permanently fix this problem, please run:
npm error   sudo chown -R 6001:6001 "/root/.npm"
npm error Log files were not written due to an error writing to the directory: /root/.npm/_logs
npm error You can rerun the command with `--loglevel=verbose` to see the logs in your terminal
```

I tried it with a simple approach first, adding my custom commands in the entrypoint:
```
    entrypoint: /bin/bash -c "npm install @bahmutov/cypress-esbuild-preprocessor @badeball/cypress-cucumber-preprocessor"
```

SSHing into the cypress container and trying to chmod the folder was not possible either, as sudo is not available.

Am I missing something or is this a problem with the official dockerimage?

**Comment by rfay** [comment]
You probably have to add a build: section in the docker-compose.cypress.yaml

@tyler36 is out for a few weeks but will be back :)

**Comment by bserem** [comment]
The `build` section kind of worked. I added a custom dockerfile like:

```Dockerfile
FROM cypress/included:13.15.2

# Set the working directory
WORKDIR /e2e

# Install npm package(s)
RUN npm install -g @bahmutov/cypress-esbuild-preprocessor @badeball/cypress-cucumber-preprocessor && npm cache clean --force
```

The container starts now, no issues there. But the plugins are still not installed, or not discoverable by Cypress.

Thanks for info and docker lessons, I'll get to the bottom of it :)

**Comment by tyler36** [comment]
@bserem 

I have found that the cypress-included image automatically find and load any cypress addon installed via NPM.
I have a couple of projects that use "@badeball/cypress-cucumber-preprocessor" too, and Cypress (via this addon) has no problems using them.

Screen shot below of cypress-cucumber-preprocessor using a Japanese-locale `.feature` spec file:

![image](https://github.com/user-attachments/assets/5b95aee2-654d-4243-b798-badc7f1ac30c)

**Comment by tyler36** [comment]
> I understand you are running npm in the host or the web container, rather than inside cypress container? Am I right?

Use `ddev npm ...` to install inside the web container. This prevents npm version conflicts between the host and DDEV (web container). This should also work if you prefer YARN (`ddev yarn ...`).

**Comment by tyler36** [comment]
While install cypress plugins in the cypress container could work, I find using `ddev npm ... --save-dev` a simplier solution. It lets the package manager do what its designed to do, manage packages.  😄

**Comment by tyler36** [comment]
I'm going to close this for now.

See above for a suggested workaround.

Happy to discuss it further/ reopen if you feel strongly about it.
