### ISSUE TITLE
Consider adding cypress under `tests` folder

### ISSUE THREAD

**Issue by bserem** [tyler36/ddev-cypress#51]
It is not uncommon for a project to have multiple test tools ([ddev-backstop](https://github.com/mmunz/ddev-backstopjs), behat etc). I consider keeping all of them under `DDEV_APPROOT/tests` good practice, as it keeps the main directory tidier and allows easy removal of a toolset if/when it gets deprecated (or easy moving to another project if they share similarities).

```
tests/
├── backstop-starterkit
├── behat
└── cypress
```

Currently ddev-cypress doesn't follow that practice. This has the extra downsides that:
- you can't have a separate `packages.json` file for Cypress, it will write to the one used by the main project
- Cypress adds some extra files (`core`, `cypress.config.js`) outside of the `cypress` folder that are polluting the repo-root

I am suggesting something like:

```diff
diff --git a/docker-compose.cypress.yaml b/docker-compose.cypress.yaml
index dbe3efb..87730f5 100644
--- a/docker-compose.cypress.yaml
+++ b/docker-compose.cypress.yaml
@@ -21,7 +21,7 @@ services:
 
     volumes:
       # Mount the project root to Cypress's project point
-      - "${DDEV_APPROOT}:/e2e"
+      - "${DDEV_APPROOT}/tests/cypress:/e2e"
       # Mount DDEV to allow commands
       - ".:/mnt/ddev_config"
       # Allow X11 forwarding
```

In this case, `cypress.config.js` will live under `tests/cypress`, we'll have a unique `package.json` just for cypress **but** all tests will be under `/tests/cypress/cypress/e2e`.
Note the **duplicate** `cypress` folder, one made by us and the other by the docker container.

I'd love to hear peoples thoughts on that.

Thanks

**Comment by tyler36** [comment]
In the current implementation, we mount the project root to Cypress's project point, `"${DDEV_APPROOT}:/e2e"`.
This allows Cypress to discover Cypress plugins installed in your project's `node_modules`.

To change the location of Cypress tests, you need to update `cypress.config.js` in your project root folder.

Eg. To discover tests in your projects `tests/cypress` directory.

```js
export default {
  e2e: {
    specPattern: 'tests/cypress/**/*.{cy.js,spec.js}',
  ...
```

See [`specPattern` configuration](https://docs.cypress.io/app/references/configuration#e2e)

**Comment by tyler36** [comment]
Thank you for the update.

I recommend creating a simple demo project and play around with test location and custom commands location. Once you get the hang of it, it will be easier to migrate an active project, should you desire.

Best of luck!
